-- Пользователи Moodle остаются в public. Назначения и попытки — в схеме attestation.

CREATE SCHEMA IF NOT EXISTS attestation;

CREATE TABLE IF NOT EXISTS mdl_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth VARCHAR(20) NOT NULL DEFAULT 'manual',
    confirmed SMALLINT NOT NULL DEFAULT 1,
    deleted SMALLINT NOT NULL DEFAULT 0,
    suspended SMALLINT NOT NULL DEFAULT 0,
    mnethostid BIGINT NOT NULL DEFAULT 1,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    idnumber VARCHAR(255),
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    institution VARCHAR(255),
    department VARCHAR(255),
    city VARCHAR(120),
    country CHAR(2),
    lang VARCHAR(30) NOT NULL DEFAULT 'ru',
    timezone VARCHAR(100) NOT NULL DEFAULT 'Europe/Moscow',
    timecreated BIGINT NOT NULL,
    timemodified BIGINT NOT NULL,
    role VARCHAR(32),
    CONSTRAINT mdl_user_username_uk UNIQUE (mnethostid, username)
);

ALTER TABLE mdl_user ADD COLUMN IF NOT EXISTS role VARCHAR(32);

CREATE TABLE IF NOT EXISTS attestation.test_assignment (
    id VARCHAR(36) PRIMARY KEY,
    listener_id BIGINT NOT NULL,
    test_code VARCHAR(64) NOT NULL,
    assigned_by BIGINT NOT NULL,
    assigned_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS attestation.attestation_attempt (
    id VARCHAR(36) PRIMARY KEY,
    listener_id BIGINT NOT NULL,
    assignment_id VARCHAR(36),
    test_code VARCHAR(64) NOT NULL,
    test_title VARCHAR(255) NOT NULL,
    started_at BIGINT NOT NULL,
    finished_at BIGINT,
    score_percent INTEGER,
    passed BOOLEAN,
    right_answers INTEGER,
    questions_count INTEGER
);
