server:
  port: 8080

spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:postgresql://localhost:5432/moodle
    username: moodle
    password: moodle
  sql:
    init:
      mode: never

test:
  passing-score: 80
  time-limit-seconds: 600
  locale: ru
